name: GitHub Actions Demo

on:
  push:
    branches:
      -main
    paths-ignore: [.github/**]
  pull_request:
    branches:
    - main
  schedule:
  - cron: "15 6 * * 0"
  workflow_dispatch:

jobs:
  Build:
    name: My Build Job
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "name of the event that triggered the workflow : ${{ GITHUB_EVENT_NAME }}"
          echo "name of the branch that the repository is currently referencing : ${{ GITHUB_HEAD_REF }}"
      - uses: actions/checkout@v3.3.0
      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
